#!/usr/bin/env node

var summer = require('./summer.js');

process.stdin.resume();
process.stdin.setEncoding('utf8');

var data = "";

process.stdin.on('data', function(chunk) { data += chunk; });
process.stdin.on('end', function() {
    process.stdout.write(data);
    var sum = summer.sum(data);
    process.stdout.write("\n" + sum + "\n");
    process.stdin.end();
});
