#!/usr/bin/env node

var summer = require('./summer.js');

var _ = require('dry-underscore');

process.stdin.resume();
process.stdin.setEncoding('utf8');

var data = "";

process.stdin.on('data', function(chunk) { data += chunk; });
process.stdin.on('end', function() {
    process.stdout.write(data);
    var sum = summer.sum(data);
    sum = _.round(sum, 2);
    process.stdout.write(sum + "\n");
});
